### ISSUE TITLE
"Baby's first battery" quest doesn't detect properly

### ISSUE THREAD

**Issue by Aciho** [rockobonaparte/bfsr#2]

**Comment by rockobonaparte** [comment]
Already fixed in f3f9a912872466ef732f8634f85a94bef28b9b5d but not deployed yet. I've been doing a dry run myself to see what all is wrong. I'm intending to roll out cumulative fixes this weekend; probably Sunday, December 20th, 2015.

The problem seems to be some Thermal Expansion metadata changes between versions. I had to reassert all the TE detection quests and their respective rewards. You can spawn in a cheat book with /hqm edit and just mark off the quest as completed meanwhile.
