### ISSUE TITLE
Ender ore

### ISSUE THREAD

**Issue by Aciho** [rockobonaparte/bfsr#7]
I realise you probably don't give a shit about bugs for the 1.7.10 version, but I'm playing it so you're getting them.  Two ender ore issues:

1) Veinminer doesn't work on it. This is because it has the same light-up-on-contact mechanic that redstone does, and veinminer doesn't recognise the lit and unlit versions as different.

2) Ender ore in RFTools worlds is broken as fuck. It has the same rarity and power requirements as most common stone, but gives you ender pearls and fucktons of XP, to the point of totally eclipsing other XP generation methods. It should probably have roughly the same stats as diamond ore or something.

**Comment by rockobonaparte** [comment]
I still care, but I might not have a convenient means to replicate
anything. It is also likely these are fundamental problems with RFTools,
Artifice, and VeinMiner. If I can configure it away, then I can address it.

It will be a little bit before I can check this. If your kung fu is strong,
you might be able to help me sooner. These are the things I need to figure
out:
1. Have VeinMiner, Artifice, and RFTools been updated? I would need to
   update them first if this winds up being bugs in their mods.
2. Do the block IDs change for lit ender ore? If so, I can probably add it
   to VeinMiner. However, I have some doubt that will carry over to unlit
   versions in a pocket.

The RFTools dimension thing is trippy. Are these just huge ore pockets or
something? I have no basis for figuring out what that is about.

It is most likely I cannot fix them because the issues are in the actual
mods, but I can forward bug reports. People do sometimes deal with them.

**Comment by Aciho** [comment]
Sorry, I'll try and be clearer.

1) This is on a server, but I'll try and replicate on a local copy, shouldn't be a problem.
2) Yeah, that's the issue. You can veinmine all the lit ore (if you tap a few first to light it up), but it doesn't propagate to the unlit ore, and it's obviously not possible to mine unlit ore. I guess there's some override put in for redstone, but I haven't looked at veinminer to find out if it's hardcoded or something you can configure.

On RFTools - this is to do with the RFTools random dimension building system. It's similar to mystcraft if you ever played with that. You stick a bunch of descriptors for things like red sky, or ocean + lava, or whatever into a dimension builder and it makes a world you can teleport to. The issue is that the ender ore descriptor is balanced as if it's regular stone (rarity 1, 300rf/tick to keep powered) when it should be high rarity and require vast amounts of power to keep running. It's not a bug in the sense of anything being broken, but I can easily create 'Infinite XP And Ender Pearls World' and power it with a few solar panels, which seems OP even in a pack that doesn't particularly care about balance. Again I'm assuming this shit is configurable, but I haven't actually looked.

**Comment by Aciho** [comment]
Check out veinminer/general.cfg, in particular equalBlocks. That should solve the first issue.

**Comment by Aciho** [comment]
You can configure rftools in config/rftools/dimlets.cfg - I would just copy the emerald ore values for ender ore. I haven't tested either of these yet but it looks like it should work.

**Comment by rockobonaparte** [comment]
I'll nibble on both over the next, well, 48 hours. Between that and having to make a server pack release that isn't ridiculously huge, I have enough to put something out. I'd presume that McJty would appreciate having an updated dimlet cost for the ore. I don't know if VeinMiner would be able to reflect those changes in its official release.

Interesting situation though: You explaining the dimension system to me has me alarmed because I have quests in BFSR to build dimensions. I added them in the beta phase and merged that into the normal releases many months ago. I'm worried about this because there hasn't been much noise about any of that stuff. None of the YouTube playthroughs appeared to update with the newest additions, and I haven't had much commentary on it. I put about half a year of effort into it. So are you up-to-date and have the changes made it into your game?

**Comment by Aciho** [comment]
I'll let you into a secret - I haven't actually opened the quest book, because I know how all the mods work, so I've just been building shit. Other people are following the quests, but I don't think they've got to that stage yet. I'll check tonight if the rftools quests are in there.

**Comment by Aciho** [comment]
Yeah, the Philadelphia experiment stuff is all in there, so I guess I'm up to date. I'd imagine most people just haven't got to the bottom of the list yet.

**Comment by rockobonaparte** [comment]
Wait--you got an ender ore dimlet? I don't even see one mentioned in the configuration.

**Comment by rockobonaparte** [comment]
Looks like I got it. It helps to call it "oreender" in the config rather than "enderore" =/. A dimlet showed up for it with high rarity so I think that came through. I would just send you the files, but you're in a pickle since you're running on a server. I'm planning to update RFTools, VeinMiner, ChickChunks, RTG, and whatever loose ends I can find before pushing a release.

**Comment by rockobonaparte** [comment]
I updated the pack the 1.7.10.4. Check my work. I forgot to commit the config changes here, but I will, tag it, and close the issue if all looks okay.

**Comment by rockobonaparte** [comment]
Fixed in a8783631c0237f3d8b1d70c0c527789fcf81a0d0
